[tools]


[tasks."0-build"]
dir="{{cwd}}/edit"
description = "Compile le projet React"
run = "npm run build && cp -rf dist/* ../ && mv ../index.html ../index.htm"
sources = ["edit/src/**/*"]

[tasks."1-serve"]
description = "Compile et lance nginx en local"
run = "npm run nginx:prepare && npm run build && npm run nginx:start"
